services:
    form_handler.provider.simple:
        class: Hostnet\Component\Form\Simple\SimpleFormProvider
        arguments:
            - "@form.factory"

    hostnet.form_handler.registry:
        class: Hostnet\Bundle\FormHandlerBundle\Registry\LegacyHandlerRegistry
        arguments:
            - "@service_container"
            - !tagged_iterator form.handler

    hostnet.form_handler.factory:
        class: Hostnet\Component\FormHandler\HandlerFactory
        arguments:
            - "@form.factory"
            - "@hostnet.form_handler.registry"

    Hostnet\Component\Form\FormProviderInterface: '@form_handler.provider.simple'
    Hostnet\Component\FormHandler\HandlerFactoryInterface: '@hostnet.form_handler.factory'
